    name: GitHub Classroom Workflow

    on: 
        [push, workflow_dispatch]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        if: ( github.event_name == 'workflow_dispatch' ) || ( ( github.event_name == 'push' ) && ( github.event.pusher.name == 'github-classroom[bot]') )         
        steps:
          - uses: actions/checkout@v2
            with:
                fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          - name: setup Java 14
            uses: actions/setup-java@v1
            with:
                java-version: 14           
          - uses: education/autograding@v1
            id: autograder
            continue-on-error: true
          - name: make dir
            run: |
              mkdir -p .github/badges
              rlink="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
              rlink="${rlink//\//\\\/}"
              sed -i "1s/.*/[reslink]: $rlink/" README.md
              wklink="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/workflows/classroom.yml"
              wklink="${wklink//\//\\\/}"              
              sed -i "2s/.*/[worklink]: $wklink/" README.md
          - name: points badge
            uses: emibcn/badge-action@v1
            with:
                LABEL: 'Points'
                STATUS: ${{ steps.autograder.outputs.points }}
                COLOR: cyan
                path: '.github/badges/points.svg'
                
          - name: Upload badge as artifact
            uses: actions/upload-artifact@v2
            with:
                name: badge
                path: '.github/badges/points.svg'
                if-no-files-found: error
          - name: Commit badge
            run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add '.github/badges/points.svg'
                git add 'README.md'
                git commit -m "Tests run, points updated"
            continue-on-error: true
          - name: Push points commit
            uses: ad-m/github-push-action@master
            if: success()
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
          - name: run tests again
            if: steps.autograder.outcome != 'success'
            uses: education/autograding@v1
